server:
  port: 8081

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      
      routes:
        - id: users
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/gateway/users/**
          filters:
            - RewritePath=/gateway/users/(?<remaining>.*), /${remaining}

        ### NEW HEALTH CHECK ROUTE ###
        - id: health-check
          uri: https://backend:8443
          predicates:
            - Path=/api/v1/health
          filters:
            - RewritePath=/api/v1/health, /actuator/health
      httpclient:
        ssl:
          use-insecure-trust-manager: true

  jwt:
    access-token-exp-ms: 60000
    refresh-token-exp-ms: 2592000000
    access-token-secret: "placeholder-access-secret"
    refresh-token-secret: "placeholder-refresh-secret"

eureka:
  client:
    enabled: false