spring.mail.username=lightbringher13@gmail.com
spring.mail.password=jlqb rnee cwds xgfq

# JWT secrets (use strong random keys!)
jwt.access-token-secret=4SfzUjVhjjpPUb2viRdvU6YaAxnYzBWodq127Zzvpo3I0QeO3T6JZm+uQSx/hd4SxKLpT+ocnmXxjJ7EL8euHw==
jwt.refresh-token-secret=ZxPDz+c/Crh5VnTgAG7326UoMOE7rTm8XvzvDrmM1VJjLk3kJ8qC4Y+YfYpYw+3aTepj3F5H7zXQMEhN7TpGqg==